spring.application.name=online_pharmacy

server.port=8099

spring.datasource.url=jdbc:mysql://54.163.6.114:3306/pharmacy

spring.datasource.username=root
spring.datasource.password=acetcse

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
